services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: backend
    depends_on:
      - db
    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/task_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8000:4000

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task_db
    ports:
      - 5432:5432
