CREATE TABLE IF NOT EXISTS tasks (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    due_date TIMESTAMP NOT NULL
);
